apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: az://dvc-store/models/churn_model.pkl
