apiVersion: v1
kind: Namespace
metadata:
  name: churn-model
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: churn-model
  annotations:
    serving.kserve.io/azure-storage-account-name: churnmlops2025
type: Opaque
stringData:
  AZURE_STORAGE_ACCESS_KEY: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-azure-access
  namespace: churn-model
secrets:
- name: azure-storage-secret